export const environment = {
  production: true,
  apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjODUxYmUzNy0xMmZjLTQzNmItYTIyYS1lNTk2MTkxNjUwMjUiLCJlbWFpbCI6InJ1YW5zYW5jaGV6QGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJSdWFuIiwibmJmIjoxNjk2NDQ5ODI3LCJleHAiOjE2OTY0Nzg2MjcsImlhdCI6MTY5NjQ0OTgyNywiaXNzIjoiZUFnZW5kYSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QifQ.x4ZKOb9IhsmOOPbr9paz5bLEf7F3pLosJvqNzFCArV4'
};
