export const environment = {
  production: true,
  apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjODUxYmUzNy0xMmZjLTQzNmItYTIyYS1lNTk2MTkxNjUwMjUiLCJlbWFpbCI6InJ1YW5zYW5jaGV6QGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJSdWFuIiwibmJmIjoxNjk3NDExOTEyLCJleHAiOjE2OTc0NDA3MTIsImlhdCI6MTY5NzQxMTkxMiwiaXNzIjoiZUFnZW5kYSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QifQ.BX6ZZWmlSee_kOXDoLtEg8A7gJSXonyuYt2peuhzEyQ'
}