export const environment = {
  production: false,
  apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjODUxYmUzNy0xMmZjLTQzNmItYTIyYS1lNTk2MTkxNjUwMjUiLCJlbWFpbCI6InJ1YW5zYW5jaGV6QGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJSdWFuIiwibmJmIjoxNjk2OTU4MjU3LCJleHAiOjE2OTY5ODcwNTcsImlhdCI6MTY5Njk1ODI1NywiaXNzIjoiZUFnZW5kYSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QifQ.AmQ79aW92apWFvVoBt8gzONzgPcqWWZIgGiWGlPFpMo'
};
