export const environment = {
  production: false,
  apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjODUxYmUzNy0xMmZjLTQzNmItYTIyYS1lNTk2MTkxNjUwMjUiLCJlbWFpbCI6InJ1YW5zYW5jaGV6QGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJSdWFuIiwibmJmIjoxNjk3MjIwODgyLCJleHAiOjE2OTcyNDk2ODIsImlhdCI6MTY5NzIyMDg4MiwiaXNzIjoiZUFnZW5kYSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QifQ.M4hJ5d9ywLBTz3Mi4WW4htm-DuJ0mQfBYYed5Vz_wzM'
};
