export const environment = {
  production: true,
  apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjODUxYmUzNy0xMmZjLTQzNmItYTIyYS1lNTk2MTkxNjUwMjUiLCJlbWFpbCI6InJ1YW5zYW5jaGV6QGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJSdWFuIiwibmJmIjoxNjk3NTAyNzA5LCJleHAiOjE2OTc1MzE1MDksImlhdCI6MTY5NzUwMjcwOSwiaXNzIjoiZUFnZW5kYSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QifQ.7URZxbmLNuh56BHcYE6csWZD-9ymv8O3B3i1mty-4SI'
}